const Constants = {
  USER: 'USER',
  API_ACCESS_TOKEN: 'API_ACCESS_TOKEN',
  API_ACCESS_HEADERS: 'API_ACCESS_HEADERS',
  API_SECRET_KEY: 'b85fF96d-7Aa4-4Ec1-bf1D-2133c1A45656',
  API_ACCESS_USER_TOKEN: 'API_ACCESS_USER_TOKEN',
  ORDER_INFO: 'ORDER_INFO',
  PAYMENT_TYPE: 'PAYMENT_TYPE',
  // ORDER_DETAIL: 'ORDER_DETAIL',
  // PAYMENT_INFO: 'PAYMENT_INFO',
  SETTING_SWAN_MODE: 'SETTING_SWAN_MODE',
  //急速模式 默认开关： true
  SETTING_SWAN_MODE_DEFAULT: true,
  PAYING: 'PAYING',
  USELIST:'USELIST',
  NOUSELIST:'NOUSELIST',
};
export default Constants
